apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Chart.Name "-be-deployment" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: be
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: be
    spec:
      containers:
      - name: be
        image: {{ print (default "" .Values.images.repository ) (default "dynamocker-be" .Values.images.beImage) ":" (default "0.0.6" .Values.images.beTag)  }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.pullPolicy }}
        ports:
        - containerPort: {{ default 8150 .Values.beService.port }}
        {{- if .Values.mockFolder.enabled}}
        volumeMounts:
        - mountPath: /mocks
          name: dynamocker-be-mockapi-folder
        env:
          - name: DYNA_MOCK_API_FOLDER
            value: '/mocks/'
      volumes:
      - name: dynamocker-be-mockapi-folder
        hostPath:
          path: {{ required "beMockFolder is a required value" .Values.mockFolder.beMockFolder }}
        {{end}}