apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-be-service'
spec:
  selector:
    tier: be
  ports:
  - name: be-port
    protocol: TCP
    port: {{ default 8151 .Values.beService.port }}
    targetPort: 8151