apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-fe-service'
spec:
  selector:
    tier: fe
  ports:
  - name: fe-port
    protocol: TCP
    port: {{ default 8150 .Values.feService.port }}
    targetPort: 8150