replicaCount: 1

installUi: true

minikube:
  enabled: true

images:
  repository:
  pullPolicy: IfNotPresent
  beImage: dynamocker-be
  beTag : 0.0.1
  feImage: dynamocker-fe
  feTag : 0.0.1

nameOverride: ""
fullnameOverride: ""

feService:
  internalPort: 8151
  externalPort: 31518

beService:
  internalPort: 8150
  externalPort: 30518

mockFolder:
  enabled: true
  beMockFolder: /home/mock-apis
