replicaCount: 1

installUi: true

minikube:
  enabled: true

images:
  repository: raffarus/
  pullPolicy: IfNotPresent
  beImage: dynamocker-be
  beTag : 0.0.6
  feImage: dynamocker-fe
  feTag : 0.0.6

nameOverride: ""
fullnameOverride: ""

feService:
  port: 8151
  nodePort: 31518

beService:
  port: 8150
  nodePort: 30518

mockFolder:
  enabled: true
  # in case of minikube, this path must coincide with the 
  # path on the minikube node:
  #   $ minikube mount <local_path>:<path_on_minikube_node>
  beMockFolder: /home/mock-apis 
