apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ print .Chart.Name "-be-deployment" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: be
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: be
    spec:
      containers:
      - name: be
        image: {{ print (default "raffarus/" .Values.repository) (default "dynamocker-be" .Values.images.beImage) ":" (default "0.0.1" .Values.images.beTag)  }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.pullPolicy }}
        ports:
        - containerPort: {{ default 8150 .Values.beService.port }}