services:
  dynamocker-be:
    build:
      context: ../
      dockerfile: ./docker/be.Dockerfile
    ports:
    - ${BE_PORT}:8150
    volumes:
    - ${MOCK_API_FOLDER}:/mocks
  dynamocker-fe:
    build:
      context: ../
      dockerfile: ./docker/fe.Dockerfile
    ports:
    - ${FE_PORT}:8151
    depends_on:
    - dynamocker-be