openapi: 3.0.0
info:
  title: Dynamocker APIs
  description: List of APIs exposed by Dynamocker server.
  version: 0.1.0
servers:
  - url: http://localhost:8150
    description: Server hosted by default on port 8150
paths:
  /mock-api:
    get:
      summary: Returns the list of mock APIs.
      description: Get the full list of mock APIs stored on the server
      responses:
        '200':
          description: List of mock APIs
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/mockApi'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: Delete the entire list of mock APIs
      description: Demand all the mock-api to be removed
      responses:
        '204':
          description: All the mock APIS have been removed
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /mock-api/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Name used to identify the mock api.
        schema:
          type : string
    post:
      summary: Add a specific mock-api.
      description: Provide a new structure for the mock-api that you want to add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/mockApi"
      responses:
        '204':
          description: The mock api has been added
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    patch:
      summary: Modify a specific mock-api.
      description: Provide a new structure for the mock-api that you want to modify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/mockApi"
      responses:
        '204':
          description: The requested modifications have been applied
        '404':
          description: The mock-api for which you request modifications cannot be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: Delete a specific mock-api
      description: Demand a mock-api to be removed
      responses:
        '204':
          description: The requested modifications have been applied
        '404':
          description: The mock-api for which you request modifications cannot be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
    errorResponse:
        type: object
        properties:
          errorResponse:
            type: string    
        required:
        - errorResponse
    mockApi:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        filePath:
          type: string
        added:
          type: string
        lastModified:
          type: string
        responses:
          type: object
          properties:
            get:
              type: json
            post:
              type: json
            delete:
              type: json
            patch:
              type: json
          minProperties: 1

      required:
        - "name"
        - "url"
        - "filePath"
        - "responses"
    


