apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-be-service'
spec:
  selector:
    tier: be
  type : NodePort
  ports:
  - name: be-port
    port: {{ default 8150 .Values.beService.port  }}
    nodePort : {{ default 30518 .Values.beService.NodePort }}
    targetPort: 8150