replicaCount: 1

images:
  repository: raffarus/
  pullPolicy: IfNotPresent
  beImage: dynamocker-be
  beTag : 0.0.1
  feImage: dynamocker-fe
  feTag : 0.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:

  create: true
  
  annotations: {}
  
  name:

podSecurityContext: {}

securityContext: {}

feService:
  type: ClusterIP
  port: 8151

beService:
  type: ClusterIP
  port: 8150

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}