# If the installation is done with minikube, then we need to have a LoadBalancer
# type of service since this is automatically exposed by 'minikube tunnel'.
# The FE is reacheable at '<EXTERNAL_IP>:<.Values.feService.externalPort>' .
{{ if required ".Values.minikube.enabled required" .Values.minikube.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: dynamocker-fe-service
  labels:
    app: {{ .Chart.Name }}-fe-deployment
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
    tier: fe
  ports:
  - port: {{ default 8151 .Values.feService.internalPort  }}
    protocol: TCP
    targetPort: {{ default 8151 .Values.feService.externalPort  }}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-fe-service'
spec:
  selector:
    tier: fe
  type : NodePort
  ports:
  - name: fe-port
    port: {{ default 8151 .Values.feService.internalPort  }}
    nodePort : {{ default 31518 .Values.feService.externalPort }}
    targetPort: 8151
{{ end }}