name: Release Images

on:
  push:
    tags:
      - '*' # This gets triggered when a new tag gets pushed
  workflow_dispatch: # This allows you to trigger the workflow manually

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in
        run: |
          docker login -u ${{env.DOCKER_USER}} -p ${{env.DOCKER_PASSWORD}}

      - name: Get version
        run: |
          echo "VERSION=$(git describe --abbrev=0 | sed 's/^v//')" >> $GITHUB_ENV
          echo "images are going to be tagged with version: '${{env.VERSION}}'"

      - name: Build the images
        run: |
          docker build -t ${{env.DOCKER_USER}}/dynamocker-be:${{env.VERSION}} -f docker/be.Dockerfile --ulimit nofile=65535:65535  .
          docker build -t ${{env.DOCKER_USER}}/dynamocker-fe:${{env.VERSION}} -f docker/fe.Dockerfile --ulimit nofile=65535:65535  .

      - name: Push the images
        run: |
          docker push ${{env.DOCKER_USER}}/dynamocker-fe:${{env.VERSION}}
          docker push ${{env.DOCKER_USER}}/dynamocker-be:${{env.VERSION}}
